# Configuração do provedor de email (AWS ou OCI)
  mail:
    integracao: AWS

# Configurações da aplicação
server:
  port: 8088
  servlet:
    # Caminho base da API
    context-path: /api/v1

# Configurações de logging
logging:
  level:
    com:
      viasoft:
        emailservice: DEBUG
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Configurações do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Informações da aplicação
info:
  app:
    name: Email Service
    description: Serviço de envio de emails com adaptação para múltiplos provedores
    version: 1.0.0
