# .docker/docker-compose.yml
services:
  email-service:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: email-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
      - MAIL_INTEGRACAO=AWS
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - email-network
    volumes:
      - ../logs:/app/logs

networks:
  email-network:
    driver: bridge

volumes:
  email-logs:
    driver: local